# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='events',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x65vent.proto\x12\x06\x65vents\">\n\nEventProto\x12\x11\n\ttimestamp\x18\x01 \x02(\x06\x12\x0e\n\x06userId\x18\x02 \x02(\x06\x12\r\n\x05\x65vent\x18\x03 \x01(\t')
)




_EVENTPROTO = _descriptor.Descriptor(
  name='EventProto',
  full_name='events.EventProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='events.EventProto.timestamp', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='events.EventProto.userId', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='events.EventProto.event', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['EventProto'] = _EVENTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventProto = _reflection.GeneratedProtocolMessageType('EventProto', (_message.Message,), dict(
  DESCRIPTOR = _EVENTPROTO,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:events.EventProto)
  ))
_sym_db.RegisterMessage(EventProto)


# @@protoc_insertion_point(module_scope)
